# The secrets file should not be checked into Git. It's published only for demonstration purpose.
secretGenerator:
- name: mysql-root-pass
  literals:
  - password=R00t
- name: mysql-user-pass
  literals:
  - username=callicoder
  - password=c@ll1c0d3r 
- name: mysql-db-url
  literals:
  - database=polls
  - url=jdbc:mysql://polling-app-mysql:3306/polls?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
resources:
  - mysql-deployment.yaml
  - polling-app-server.yaml
  - polling-app-client.yaml  













# kubectl -n polls create secret generic mysql-root-pass --from-literal=password=R00t


# kubectl -n polls create secret generic mysql-user-pass --from-literal=username=callicoder --from-literal=password=c@ll1c0d3r


# kubectl -n polls create secret generic mysql-db-url --from-literal=database=polls --from-literal=url='jdbc:mysql://polling-app-mysql:3306/polls?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false'






